name: OpenMRS CI

on:
  workflow_dispatch:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  release:
    types:
      - created

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

jobs:
  build:
    uses: teenthofabud/openmrs-contrib-gha-workflows/.github/workflows/build-frontend-module.yml@main
    with:
      pre_verify_command: yarn check-translations
      verify_command: yarn verify
